use_frameworks!

target 'XTFrameModule_Example' do
  pod 'XTFrameModule', :path => '../'

  target 'XTFrameModule_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
